name: Telegram
description: A simple telegram bot
version: 1.0.0
homepage: https://github.com/theKAKAN/TelegramBot
author: KAKAN

environment:
  sdk: '>=2.0.0-dev.52.0 <2.0.0'

dependencies:
  teledart: "^0.0.7"
  log: "^0.0.6"
